name: dev
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - asttokens=3.0.1
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - comm=0.2.3
  - cpython=3.13.9
  - debugpy=1.8.17
  - decorator=5.2.1
  - executing=2.2.1
  - icu=75.1
  - importlib-metadata=8.7.0
  - ipykernel=7.1.0
  - ipython=9.7.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - keyutils=1.6.3
  - krb5=1.21.3
  - ld_impl_linux-64=2.45
  - libblas=3.11.0
  - libcblas=3.11.0
  - libedit=3.1.20250104
  - libexpat=2.7.3
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - liblapack=3.11.0
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libopenblas=0.3.30
  - libsodium=1.0.20
  - libsqlite=3.51.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=2.41.2
  - libzlib=1.3.1
  - matplotlib-inline=0.2.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numpy=2.3.5
  - openssl=3.6.0
  - packaging=25.0
  - pandas=2.3.3
  - parso=0.8.5
  - pexpect=4.9.0
  - pip=25.3
  - platformdirs=4.5.0
  - prompt-toolkit=3.0.52
  - psutil=7.1.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.13.9
  - python-dateutil=2.9.0.post0
  - python-gil=3.13.9
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytz=2025.2
  - pyzmq=27.1.0
  - readline=8.2
  - six=1.17.0
  - stack_data=0.6.3
  - tk=8.6.13
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - tzdata=2025b
  - wcwidth=0.2.14
  - zeromq=4.3.5
  - zipp=3.23.0
prefix: /opt/conda/envs/dev
